CREATE TABLE dress_style (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE dress_type (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE product (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    style_id       BIGINT NOT NULL REFERENCES dress_style(id),
    type_id        BIGINT NOT NULL REFERENCES dress_type(id),
    name           VARCHAR(255) UNIQUE NOT NULL,
    price          DECIMAL(10,2) NOT NULL,
    description    VARCHAR(4000),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE product_variant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    color         VARCHAR(255) NOT NULL,
    size          VARCHAR(10) NOT NULL,
    stock         INT NOT NULL DEFAULT 0,

    CONSTRAINT size_check CHECK (
        size IN (
            'XXS',
            'XS',
            'S',
            'M',
            'L',
            'XL',
            'XXL'
        )
    )
);

CREATE TABLE product_image (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    url            VARCHAR(2000) NOT NULL,
    display_order  INT NOT NULL DEFAULT 1
);

CREATE TABLE product_review (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    rating        DECIMAL(2,1) NOT NULL,
    comment       VARCHAR(4000),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT rating_check CHECK (rating BETWEEN 1 AND 5)
);