CREATE TABLE dressStyle (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE dressType (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE product (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    styleId        BIGINT NOT NULL REFERENCES dressStyle(id),
    typeId         BIGINT NOT NULL REFERENCES dressType(id),
    name           VARCHAR(255) UNIQUE NOT NULL,
    price          DECIMAL(10,2) NOT NULL,
    description    VARCHAR(4000),
    createdAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE productVariant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productId     BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    color         VARCHAR(255) NOT NULL,
    size          VARCHAR(10) NOT NULL,
    stock         INT NOT NULL DEFAULT 0,

    CONSTRAINT sizeCheck CHECK (
        size IN (
            'XXS',
            'XS',
            'S',
            'M',
            'L',
            'XL',
            'XXL'
        )
    )
);

CREATE TABLE productImage (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productId      BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    url            VARCHAR(2000) NOT NULL,
    displayOrder   INT NOT NULL DEFAULT 1
);

CREATE TABLE productReview (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productId     BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    rating        DECIMAL(2,1) NOT NULL,
    comment       VARCHAR(4000),
    createdAt     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT ratingCheck CHECK (rating BETWEEN 1 AND 5)
);